<a href="https://colab.research.google.com/github/ulvem/Time-to-Practice-Numpy-11-24/blob/main/copy_of_time_to_practice_numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img height="180px" src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" align="left" hspace="30px" vspace="50px"/>

# Welcome to your next notebook with SDA!

During the classes we will mostly use [Google Colaboratory](https://colab.research.google.com/?hl=en) which is a free Jupyter notebook environment that requires no setup and runs entirely in the cloud.

However, for bigger projects, especially involving Deep Learning and/or big data reading, it might be a better choice to setup Jupyter Notebook or Jupyter Lab on your computer. Also, it is worth noticing that there is a great number of useful extensions (see [nbextensions](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/index.html) and [jupyter-labextension](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html)) not available for Colab users.

<img src="https://drive.google.com/uc?export=view&id=1UO2urRciECzoKE_vHy4RMGfFbkOWOGlW" alt="SDA logo" align="left" width="100px" hspace="10px" vspace="10px"/>
<br>

# TASKS

<img src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" width="150" align='right'/>
<br>

## Linear Algebra

### **<font color='#306998'>TASKS </font><font color='#ffd33b'>1.1 - 1.10</font>** should be already completed :)

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.11</font>**

For the matrix from task 1.7:
* calculate its determinant,
* calculate its trace (the sum of elements on the main diagonal),
* find the largest and smallest item.

$$
A=
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16
\end{bmatrix}
$$

In [ ]:
import numpy as np

# Define the matrix A
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Calculate the determinant of A
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)
# Calculate the trace of A
trace_A = np.trace(A)
print("Trace of A:", trace_A)
# Find the largest and smallest items in A
max_A = np.max(A)
min_A = np.min(A)
print("Largest item in A:", max_A)
print("Smallest item in A:", min_A)



Determinant of A: 0.0
Trace of A: 34
Largest item in A: 16
Smallest item in A: 1


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.12</font>**

Define two `3x3` real matrices, ie. whose elements consist entirely of real numbers. For the first matrix, draw the numbers from standard normal (Gaussian) distribution, ie. $\mu = 0$ and $\sigma = 1$. For the second one, set the standard devation to 1 and mean value to 5.

**See Appendix.**

Next, for each of them:
* multiply all elements by a scalar 10,
* extract the element in the middle,
* transpose them
* get its trace & sum of all elements

and calculate their:
* sum
* difference
* element-wise multiplication result
* element-wise division result
* matrix product (matrix multiplication)

In [ ]:
import numpy as np

# Define the matrices
A = np.random.normal(0, 1, (3, 3))
B = np.random.normal(5, 1, (3, 3))

# Multiply all elements by a scalar 10
A_scaled = A * 10
B_scaled = B * 10

# Extract the element in the middle
A_middle = A_scaled[1, 1]
B_middle = B_scaled[1, 1]

# Transpose the matrices
A_transposed = A_scaled.T
B_transposed = B_scaled.T

# Calculate the trace (sum of elements on the main diagonal)
A_trace = np.trace(A_scaled)
B_trace = np.trace(B_scaled)

# Calculate the sum of all elements
A_sum = np.sum(A_scaled)
B_sum = np.sum(B_scaled)

# Calculate their sum
sum_matrices = A_scaled + B_scaled

# Calculate their difference
difference_matrices = A_scaled - B_scaled

# Calculate element-wise multiplication
elementwise_multiplication = A_scaled * B_scaled

# Calculate element-wise division
elementwise_division = A_scaled / B_scaled

# Calculate matrix product (matrix multiplication)
matrix_product = np.dot(A_scaled, B_scaled)

# Print the results
print("Matrix A (scaled):\n", A_scaled)
print("Matrix B (scaled):\n", B_scaled)
print("Middle element of A:", A_middle)
print("Middle element of B:", B_middle)
print("Transpose of A:\n", A_transposed)
print("Transpose of B:\n", B_transposed)
print("Trace of A:", A_trace)
print("Trace of B:", B_trace)
print("Sum of all elements in A:", A_sum)
print("Sum of all elements in B:", B_sum)
print("Sum of matrices:\n", sum_matrices)
print("Difference of matrices:\n", difference_matrices)
print("Element-wise multiplication:\n", elementwise_multiplication)
print("Element-wise division:\n", elementwise_division)
print("Matrix product:\n", matrix_product)


Matrix A (scaled):
 [[  2.9705816  -11.4716069   -4.36248322]
 [ -9.31687354  -3.82540592  -4.02710867]
 [ -8.31055498   0.91517995  17.91282323]]
Matrix B (scaled):
 [[39.78750169 52.18776647 31.82693335]
 [54.23166674 60.75001494 35.23173022]
 [37.58787462 47.86003872 56.09203451]]
Middle element of A: -3.8254059174130717
Middle element of B: 60.75001493928554
Transpose of A:
 [[  2.9705816   -9.31687354  -8.31055498]
 [-11.4716069   -3.82540592   0.91517995]
 [ -4.36248322  -4.02710867  17.91282323]]
Transpose of B:
 [[39.78750169 54.23166674 37.58787462]
 [52.18776647 60.75001494 47.86003872]
 [31.82693335 35.23173022 56.09203451]]
Trace of A: 17.057998915228996
Trace of B: 156.6295511423253
Sum of all elements in A: -19.515448461579425
Sum of all elements in B: 415.555561271462
Sum of matrices:
 [[42.75808329 40.71615957 27.46445013]
 [44.9147932  56.92460902 31.20462155]
 [29.27731963 48.77521867 74.00485774]]
Difference of matrices:
 [[-36.8169201  -63.65937337 -36.18941658]
 [-

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.14</font>**

Create an array with the following elements: `[23, 45, 124, 112, 150, 43, 25, 17, 268, 254, 95, 97, 8]` and filter out the ones that are less than or equal to their mean value. How many such numbers are there?

In [ ]:
# Define the array
array = np.array([23, 45, 124, 112, 150, 43, 25, 17, 268, 254, 95, 97, 8])

# Calculate the mean value of the array
mean_value = np.mean(array)

# Filter out the elements that are less than or equal to the mean value
filtered_array = array[array <= mean_value]

# Count the number of such elements
count_filtered = len(filtered_array)

print("Filtered elements:", filtered_array)
print("Number of elements less than or equal to the mean value:", count_filtered)


Filtered elements: [23 45 43 25 17 95 97  8]
Number of elements less than or equal to the mean value: 8


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.15</font>**

Use the array defined above to evaluate mean value and standard deviation. Check how many of these numbers is within a distance of at most one standard deviation from the mean, ie. belongs to the closed interval `[mean - std, mean + std]`.

In [ ]:
# Define the array
array = np.array([23, 45, 124, 112, 150, 43, 25, 17, 268, 254, 95, 97, 8])

# Calculate the mean value of the array
mean_value = np.mean(array)
print("Mean value:", mean_value)

# Calculate the standard deviation of the array
std_deviation = np.std(array)
print("Standard deviation:", std_deviation)

# Define the interval [mean - std, mean + std]
lower_bound = mean_value - std_deviation
upper_bound = mean_value + std_deviation

# Filter the elements that fall within the interval
within_one_std = array[(array >= lower_bound) & (array <= upper_bound)]

# Count the number of such elements
count_within_one_std = len(within_one_std)

print("Elements within one standard deviation:", within_one_std)
print("Number of elements within one standard deviation:", count_within_one_std)


Mean value: 97.0
Standard deviation: 82.3958550115048
Elements within one standard deviation: [ 23  45 124 112 150  43  25  17  95  97]
Number of elements within one standard deviation: 10


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.16</font>**

Write a function `get_sum_of_squared_naturals()` that takes one argument as an input (call it `max_value`) and returns the sum of all natural numbers such that $k \leq max\_value.$

Make sure that the input given by a user is a natural number. Set the default value to 5.

In [ ]:
def get_sum_of_squared_naturals(max_value=5):
    # Check if the input is a natural number
    if not isinstance(max_value, int) or max_value <= 0:
        raise ValueError("The input must be a natural number greater than 0.")

    # Calculate the sum of the squares of all natural numbers less than or equal to max_value
    sum_of_squares = sum(k**2 for k in range(1, max_value + 1))

    return sum_of_squares

# Example usage
result = get_sum_of_squared_naturals(5)
print("Sum of squared naturals:", result)


Sum of squared naturals: 55


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.17</font>**

Create the following 4x4 matrix 4x4, and then:
* print out an element from the second row and the third column (starting from 1),
* check which element is equal to 0,
* with array indexing:
    * display element equal to 3,
    * view vector `[3, 11, 0]`,
* calculate its:
    * determinant,
    * trace (sum of diagonal entries),
    * the maximum and mininum elements,
    * the mean value of each column,
    * the maximum value of each row,
* find its transposition and multiply both matrices mathematically, ie. get the product of $A \cdot A^T,$
* determine its eigenvalues and eigenvectors. (optional)

```
np.array([
    [1, 15, 4, 13],
    [8, 21, 3, 12],
    [11, 13, 11, 5],
    [32, 13, 0, 2]
])
```

In [ ]:
# Define the matrix A
A = np.array([
    [1, 15, 4, 13],
    [8, 21, 3, 12],
    [11, 13, 11, 5],
    [32, 13, 0, 2]
])

# Print out an element from the second row and the third column (starting from 1)
element_2_3 = A[1, 2]
print("Element from the second row and the third column:", element_2_3)

# Check which element is equal to 0
zero_elements = np.where(A == 0)
print("Elements equal to 0:", zero_elements)

# Display element equal to 3
element_equal_3 = np.where(A == 3)
print("Element equal to 3:", element_equal_3)

# View vector [3, 11, 0]
vector = A[:, [2, 0, 3]]
print("Vector [3, 11, 0]:", vector)

# Calculate the determinant
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

# Calculate the trace (sum of diagonal entries)
trace_A = np.trace(A)
print("Trace of A:", trace_A)

# Find the maximum and minimum elements
max_A = np.max(A)
min_A = np.min(A)
print("Maximum element in A:", max_A)
print("Minimum element in A:", min_A)

# Calculate the mean value of each column
mean_columns = np.mean(A, axis=0)
print("Mean value of each column:", mean_columns)

# Find the maximum value of each row
max_rows = np.max(A, axis=1)
print("Maximum value of each row:", max_rows)

# Find its transposition and multiply both matrices mathematically (A * A^T)
A_transposed = A.T
product_A_AT = np.dot(A, A_transposed)
print("Product of A and A^T:\n", product_A_AT)

# Determine its eigenvalues and eigenvectors (optional)
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)


Element from the second row and the third column: 3
Elements equal to 0: (array([3]), array([2]))
Element equal to 3: (array([1]), array([2]))
Vector [3, 11, 0]: [[ 4  1 13]
 [ 3  8 12]
 [11 11  5]
 [ 0 32  2]]
Determinant of A: -19963.99999999999
Trace of A: 35
Maximum element in A: 32
Minimum element in A: 0
Mean value of each column: [13.  15.5  4.5  8. ]
Maximum value of each row: [15 21 13 32]
Product of A and A^T:
 [[ 411  491  315  253]
 [ 491  658  454  553]
 [ 315  454  436  531]
 [ 253  553  531 1197]]
Eigenvalues of A: [ 41.24366578 -18.12008708   3.01436162   8.86205968]
Eigenvectors of A:
 [[-0.42552168 -0.46858888 -0.27614717  0.02912145]
 [-0.55379568 -0.17594186  0.6248671  -0.13789778]
 [-0.48050507  0.10806928 -0.19647432  0.98203903]
 [-0.53043051  0.858947   -0.70333611 -0.12544114]]


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.18</font>**

Create a 3x3 array and normalize its columns, ie. scale the values such that sum of each column equals 1 (unit vectors).

In [ ]:
# Create a 3x3 array with random values
array = np.random.rand(3, 3)

# Normalize the columns
column_sums = np.sum(array, axis=0)
normalized_array = array / column_sums

print("Original array:\n", array)
print("Normalized array:\n", normalized_array)
print("Sum of each column in the normalized array:", np.sum(normalized_array, axis=0))


Original array:
 [[0.66870303 0.63438478 0.50745085]
 [0.82549841 0.77954197 0.99703084]
 [0.25635901 0.66161158 0.75851032]]
Normalized array:
 [[0.38199368 0.30564831 0.2242389 ]
 [0.47156235 0.37558544 0.44058081]
 [0.14644396 0.31876625 0.33518029]]
Sum of each column in the normalized array: [1. 1. 1.]


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.19</font>**

Write a function that accepts a positive natural number $p\in\mathbb{N}_1$ and two NumPy vectors as an input (both of the same shape). The function should return the Mikowski distance between those vectors, ie.:
$$d_p(X, Y) = \left(\sum_{i=1}^n |x_i - y_i|^p\right)^\frac{1}{p},$$

where $X=[x_1, x_2, ..., x_n]\in\mathbb{R}^n$ and $Y=[y_1, y_2, ..., y_n]\in\mathbb{R}^n.$

*Hint: you can use the following assertions `assert a.size == b.size, "Arrays must be of the same shape"`, and `assert isinstance(input_array_1, np.ndarray)`.*

In [ ]:
def get_minkowski_distance(p, input_array_1, input_array_2):
    # Ensure the inputs are NumPy arrays
    assert isinstance(input_array_1, np.ndarray), "input_array_1 must be a NumPy array"
    assert isinstance(input_array_2, np.ndarray), "input_array_2 must be a NumPy array"

    # Ensure the arrays have the same shape
    assert input_array_1.size == input_array_2.size, "Arrays must be of the same shape"

    # Calculate the Minkowski distance
    distance = np.sum(np.abs(input_array_1 - input_array_2) ** p) ** (1 / p)

    return distance

# Example usage
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
p = 3

distance = get_minkowski_distance(p, X, Y)
print("Minkowski distance:", distance)


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.20</font>**

Determine the length of the following vectors using Euclidean norm:
* $v_1=[0, 5]$
* $v_2=[0, -3]$
* $v_3=[7, 0]$
* $v_4=[-\pi, 0]$
* $v_5=[3, -4]$
* $v_6=[1, 7]$
* $v_7=[5\sqrt{3}, -3, 4]$
* $v_8=[1, 2, 3, 4]$

*Hint: using default parameters of `numpy.linalg.norm()` function will return Frobenius norm for matrices which is equivalent to Euclidean norm for vectors:*
https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html

In [ ]:
# Define the vectors
v1 = np.array([0, 5])
v2 = np.array([0, -3])
v3 = np.array([7, 0])
v4 = np.array([-np.pi, 0])
v5 = np.array([3, -4])
v6 = np.array([1, 7])
v7 = np.array([np.sqrt(53), -3, 4])
v8 = np.array([1, 2, 3, 4])

# Calculate the Euclidean norm for each vector
norm_v1 = np.linalg.norm(v1)
norm_v2 = np.linalg.norm(v2)
norm_v3 = np.linalg.norm(v3)
norm_v4 = np.linalg.norm(v4)
norm_v5 = np.linalg.norm(v5)
norm_v6 = np.linalg.norm(v6)
norm_v7 = np.linalg.norm(v7)
norm_v8 = np.linalg.norm(v8)

# Print the results
print("Euclidean norm of v1:", norm_v1)
print("Euclidean norm of v2:", norm_v2)
print("Euclidean norm of v3:", norm_v3)
print("Euclidean norm of v4:", norm_v4)
print("Euclidean norm of v5:", norm_v5)
print("Euclidean norm of v6:", norm_v6)
print("Euclidean norm of v7:", norm_v7)
print("Euclidean norm of v8:", norm_v8)


Euclidean norm of v1: 5.0
Euclidean norm of v2: 3.0
Euclidean norm of v3: 7.0
Euclidean norm of v4: 3.141592653589793
Euclidean norm of v5: 5.0
Euclidean norm of v6: 7.0710678118654755
Euclidean norm of v7: 8.831760866327848
Euclidean norm of v8: 5.477225575051661


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.21</font>**

For the following vectors `a=[3, -2]` and `b=[-2, -3]`, determine their scalar product and the angle between these vectors.

*Correct answer $\alpha = 90^\circ$.*

In [ ]:
# Define the vectors
a = np.array([3, -2])
b = np.array([-2, -3])

# Calculate the scalar product (dot product)
dot_product = np.dot(a, b)
print("Scalar product (dot product):", dot_product)

# Calculate the magnitudes of the vectors
magnitude_a = np.linalg.norm(a)
magnitude_b = np.linalg.norm(b)

# Calculate the cosine of the angle
cos_angle = dot_product / (magnitude_a * magnitude_b)

# Calculate the angle in radians
angle_radians = np.arccos(cos_angle)

# Convert the angle to degrees
angle_degrees = np.degrees(angle_radians)
print("Angle between the vectors (in degrees):", angle_degrees)


Scalar product (dot product): 0
Angle between the vectors (in degrees): 90.0


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.22</font>**

For the following vectors `a=[0, 3]` and `b=[2, 2]`, determine their scalar product and the angle between these vectors.

*Correct answer $\alpha = 45^\circ$.*

In [ ]:
# Define the vectors
a = np.array([0, 3])
b = np.array([2, 2])

# Calculate the scalar product (dot product)
dot_product = np.dot(a, b)
print("Scalar product (dot product):", dot_product)

# Calculate the magnitudes of the vectors
magnitude_a = np.linalg.norm(a)
magnitude_b = np.linalg.norm(b)

# Calculate the cosine of the angle
cos_angle = dot_product / (magnitude_a * magnitude_b)

# Calculate the angle in radians
angle_radians = np.arccos(cos_angle)

# Convert the angle to degrees
angle_degrees = np.degrees(angle_radians)
print("Angle between the vectors (in degrees):", angle_degrees)


Scalar product (dot product): 6
Angle between the vectors (in degrees): 45.00000000000001


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.23</font>**

For the following vectors `a=[3, -2]` and `b=[1, 7]`, determine their scalar product and the angle between these vectors.

*Correct answer $\alpha ≈ 116^\circ$.*

In [ ]:
# Define the vectors
a = np.array([3, -2])
b = np.array([1, 7])

# Calculate the scalar product (dot product)
dot_product = np.dot(a, b)
print("Scalar product (dot product):", dot_product)

# Calculate the magnitudes of the vectors
magnitude_a = np.linalg.norm(a)
magnitude_b = np.linalg.norm(b)

# Calculate the cosine of the angle
cos_angle = dot_product / (magnitude_a * magnitude_b)

# Calculate the angle in radians
angle_radians = np.arccos(cos_angle)

# Convert the angle to degrees
angle_degrees = np.degrees(angle_radians)
print("Angle between the vectors (in degrees):", angle_degrees)


Scalar product (dot product): -11
Angle between the vectors (in degrees): 115.55996517182382


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.24</font>**

Normalize each vector from Task 20.

In [ ]:
import numpy as np

# Define the vectors
v1 = np.array([0, 5])
v2 = np.array([0, -3])
v3 = np.array([7, 0])
v4 = np.array([-np.pi, 0])
v5 = np.array([3, -4])
v6 = np.array([1, 7])
v7 = np.array([np.sqrt(53), -3, 4])
v8 = np.array([1, 2, 3, 4])

# Calculate the Euclidean norm for each vector
norm_v1 = np.linalg.norm(v1)
norm_v2 = np.linalg.norm(v2)
norm_v3 = np.linalg.norm(v3)
norm_v4 = np.linalg.norm(v4)
norm_v5 = np.linalg.norm(v5)
norm_v6 = np.linalg.norm(v6)
norm_v7 = np.linalg.norm(v7)
norm_v8 = np.linalg.norm(v8)

# Print the results
print("Euclidean norm of v1:", norm_v1)
print("Euclidean norm of v2:", norm_v2)
print("Euclidean norm of v3:", norm_v3)
print("Euclidean norm of v4:", norm_v4)
print("Euclidean norm of v5:", norm_v5)
print("Euclidean norm of v6:", norm_v6)
print("Euclidean norm of v7:", norm_v7)
print("Euclidean norm of v8:", norm_v8)

# Normalize the vectors
normalized_v1 = v1 / np.linalg.norm(v1)
normalized_v2 = v2 / np.linalg.norm(v2)
normalized_v3 = v3 / np.linalg.norm(v3)
normalized_v4 = v4 / np.linalg.norm(v4)
normalized_v5 = v5 / np.linalg.norm(v5)
normalized_v6 = v6 / np.linalg.norm(v6)
normalized_v7 = v7 / np.linalg.norm(v7)
normalized_v8 = v8 / np.linalg.norm(v8)

# Print the normalized vectors
print("Normalized v1:", normalized_v1)
print("Normalized v2:", normalized_v2)
print("Normalized v3:", normalized_v3)
print("Normalized v4:", normalized_v4)
print("Normalized v5:", normalized_v5)
print("Normalized v6:", normalized_v6)
print("Normalized v7:", normalized_v7)
print("Normalized v8:", normalized_v8)



Euclidean norm of v1: 5.0
Euclidean norm of v2: 3.0
Euclidean norm of v3: 7.0
Euclidean norm of v4: 3.141592653589793
Euclidean norm of v5: 5.0
Euclidean norm of v6: 7.0710678118654755
Euclidean norm of v7: 8.831760866327848
Euclidean norm of v8: 5.477225575051661
Normalized v1: [0. 1.]
Normalized v2: [ 0. -1.]
Normalized v3: [1. 0.]
Normalized v4: [-1.  0.]
Normalized v5: [ 0.6 -0.8]
Normalized v6: [0.14142136 0.98994949]
Normalized v7: [ 0.82431012 -0.33968311  0.45291081]
Normalized v8: [0.18257419 0.36514837 0.54772256 0.73029674]


<img src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" width="150" align='right'/>
<br>

## Appendix: random numbers generators

1. Randomly generated number(s) from normal (Gauss) distribution.
```python
np.random.normal()
np.random.normal(size=6)
```
1. Randomly selected numbers from the uniform system.
```python
np.random.uniform(size=6)
```
1. Randomly selected number from a specific range.
```python
np.random.randint(3, 30, size=6)
```
1. Randomly selected floating-point number
```python
np.random.random()
```